# ############################################################################
# Model: Whisper (encoder-decoder) + cross-entropy loss
# Authors: Luca Della Libera 2023
# ############################################################################

experiment_name: FT

seed: 0
__set_seed: !apply:torch.manual_seed [!ref <seed>]

skip_test: False

# Data preparation
base_locales: [en, zh-CN, de, es, ru, fr, pt, ja, tr, pl]
new_locales: [rw, eo, kab, lg, mhr, ckb, ab, kmr, fy-NL, ia]
data_folder: !PLACEHOLDER
max_durations: [36000, 3600, 3600]  # Maximum total durations in seconds for train, dev, and test splits for each locale

# Output directories
output_folder: !ref results/<whisper_variant>/<experiment_name>/<seed>
save_folder: !ref <output_folder>/save

# Training parameters
train_batch_size: 6
valid_batch_size: 16
train_num_workers: 6
valid_num_workers: 6

sample_rate: 16000
sorting: ascending
avoid_if_longer_than: 10  # Remove utterances longer than 10s (open microphones)

ignore_index: -100  # For cross-entropy loss
label_smoothing: 0

num_epochs: 2
lr: 0.0001
improvement_threshold: 0.0025
annealing_factor: 0.8

whisper_variant: whisper-large-v2
encoder_only: False
freeze: True
freeze_encoder: True

max_target_length: 448  # Must be <= 448 (Whisper maximum target length)
nonfinite_patience: 10
max_grad_norm: 5.0
precision: fp16
gradient_checkpointing: False
ckpt_interval_minutes: 600

max_gen_tokens: 80
forced_decoder_locale: null  # Set dynamically
normalize_transcripts: True

# Dataloader options
train_dataloader_kwargs:
    batch_size: !ref <train_batch_size>
    num_workers: !ref <train_num_workers>

valid_dataloader_kwargs:
    batch_size: !ref <valid_batch_size>
    num_workers: !ref <valid_num_workers>

# Adapter Config
adapter_configuration:
    d_conv: 4
    d_state: 16
    expand: 2
    reduction_factor: 64
    is_bidirectional: False
    is_noncausal: True
    conv_down_proj: False
    is_parallel: False
    non_linearity: 'None'
    adapter_config: 'shared_scaled_par_mamba'

# Modules
whisper: !new:model.ProgressiveWhisperWithAdapters
    source: !ref openai/<whisper_variant>
    save_path: !ref <save_folder>/checkpoint
    sampling_rate: !ref <sample_rate>
    encoder_only: !ref <encoder_only>
    freeze: !ref <freeze>
    freeze_encoder: !ref <freeze_encoder>
    adapter_config: !ref <adapter_configuration>

ce_loss: !new:torch.nn.CrossEntropyLoss
    ignore_index: !ref <ignore_index>
    label_smoothing: !ref <label_smoothing>

modules:
    whisper: !ref <whisper>

# Optimizers
opt_class: !name:torch.optim.AdamW
    lr: !ref <lr>

lr_annealing: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: !ref <improvement_threshold>
    annealing_factor: !ref <annealing_factor>
    patient: 0

# Performance metrics
wer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

cer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
    split_tokens: True

# Counters, checkpointers, loggers, etc.
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <num_epochs>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <whisper>
        scheduler: !ref <lr_annealing>
        counter: !ref <epoch_counter>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <output_folder>/<experiment_name>.txt
